# This host variable configures the sync jobs initiated by this host.
syncoid__initiator_jobs: []
  # - 
  #   source:
  #     user: user
  #     host: remote
  #     dataset: tank/wibble
  #   sink:
  #     dataset: tank/backups/wibble
  #   syncoid_arguments:
  #     - "--compress"
  #   ssh_private_key_file:
  #   # Note on linux for pull backups local_user_account not being root I don't
  #   # think will work as you can't delegate mountpoint permissions
  #   local_user_account: # (default root)
  #   replication_frequency:
  #   cron_minute: "*/15"


# This host variable configures the host to be a target for a syncoid job.
syncoid__client_config: []
  # -
  #   user: user
  #   ssh_public_key_file:
  #   recursive: false
  #   source_datasets:
  #     - tank/wibble
  #   sink_datasets:
  #     - tank/backups/wibble
