- name: Saniod
  hosts: [ 'cadair_sanoid_hosts' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:
    - role: cadair.sanoid.install_sanoid
      tags: [ 'role::sanoid', 'skip::sanoid' ]

    - role: cadair.sanoid.sanoid
      tags: [ 'role::sanoid', 'skip::sanoid' ]
