- name: Syncoid
  hosts: [ 'cadair_syncoid_hosts' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:
    - role: cadair.sanoid.syncoid
      tags: [ 'role::syncoid', 'skip::syncoid' ]
